name = "AtomicPotentials"
uuid = "eac66916-230f-11e9-03e5-b9a8fe2fc74a"
authors = ["Stefanos Carlström <stefanos.carlstrom@gmail.com>"]
version = "0.1.0"

[deps]
AtomicLevels = "10933b4c-d60f-11e8-1fc6-bd9035a249a1"
